# base on latest python file
FROM python:latest

# add our python program
ADD manager.py infofile.py requirements.txt ./

# install dependent libraries
RUN pip install -r requirements.txt

# the command to run our program
CMD [ "python", "./manager.py"]
