# base on latest python file
FROM python:latest

# add our python program
ADD manager.py infofile.py ./

# install dependent libraries
RUN pip install pika uproot aiohttp requests

# the command to run our program
CMD [ "python", "./manager.py"]
