# base on latest python file
FROM python:latest

# add our python program
ADD worker.py requirements.txt ./

# install dependent libraries
RUN pip install -r requirements.txt

# the command to run our program
CMD [ "python", "-u", "./worker.py"]
