# base on latest python file
FROM python:latest

# add our python program
ADD queue_purge.py ./

# install dependent libraries
RUN pip install pika

# the command to run our program
CMD [ "python", "./queue_purge.py"]
